language: python
python:
  - 2.7

services: postgresql

env:
- DJANGO=1.8.3

before_install:
  - export DJANGO_SETTINGS_MODULE=sharbrary.settings
  - export PYTHONPATH=$HOME/builds/giliam/sharbrary
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
- python manage.py syncdb --noinput

branches:
  only:
    - master
